services:
  - type: web
    name: humanitarian-chat
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    disk:
      name: data
      mountPath: /opt/render/project/src
      sizeGB: 1
